run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/autonomous-bits/nomos-provider-environment-variables
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
