// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_STATUS_OK          HealthStatus = 1
	HealthStatus_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_STATUS_STARTING    HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_DEGRADED",
		3: "STATUS_STARTING",
	}
	HealthStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_DEGRADED":    2,
		"STATUS_STARTING":    3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_provider_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_proto_provider_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{0}
}

type InitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Alias          string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Config         *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	SourceFilePath string                 `protobuf:"bytes,3,opt,name=source_file_path,json=sourceFilePath,proto3" json:"source_file_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *InitRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{1}
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Struct       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{3}
}

func (x *FetchResponse) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{4}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_proto_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResponse) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=nomos.provider.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{8}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_provider_proto_rawDescGZIP(), []int{9}
}

var File_proto_provider_proto protoreflect.FileDescriptor

const file_proto_provider_proto_rawDesc = "" +
	"\n" +
	"\x14proto/provider.proto\x12\x11nomos.provider.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x84\x01\n" +
	"\vInitRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12(\n" +
	"\x10source_file_path\x18\x03 \x01(\tR\x0esourceFilePathJ\x04\b\x04\x10\v\"\x14\n" +
	"\fInitResponseJ\x04\b\x01\x10\v\"(\n" +
	"\fFetchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04pathJ\x04\b\x02\x10\v\"D\n" +
	"\rFetchResponse\x12-\n" +
	"\x05value\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05valueJ\x04\b\x02\x10\v\"\x13\n" +
	"\vInfoRequestJ\x04\b\x01\x10\v\"X\n" +
	"\fInfoResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04typeJ\x04\b\x04\x10\v\"\x15\n" +
	"\rHealthRequestJ\x04\b\x01\x10\v\"i\n" +
	"\x0eHealthResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.nomos.provider.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageJ\x04\b\x03\x10\v\"\x17\n" +
	"\x0fShutdownRequestJ\x04\b\x01\x10\v\"\x18\n" +
	"\x10ShutdownResponseJ\x04\b\x01\x10\v*_\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x02\x12\x13\n" +
	"\x0fSTATUS_STARTING\x10\x032\x93\x03\n" +
	"\x0fProviderService\x12G\n" +
	"\x04Init\x12\x1e.nomos.provider.v1.InitRequest\x1a\x1f.nomos.provider.v1.InitResponse\x12J\n" +
	"\x05Fetch\x12\x1f.nomos.provider.v1.FetchRequest\x1a .nomos.provider.v1.FetchResponse\x12G\n" +
	"\x04Info\x12\x1e.nomos.provider.v1.InfoRequest\x1a\x1f.nomos.provider.v1.InfoResponse\x12M\n" +
	"\x06Health\x12 .nomos.provider.v1.HealthRequest\x1a!.nomos.provider.v1.HealthResponse\x12S\n" +
	"\bShutdown\x12\".nomos.provider.v1.ShutdownRequest\x1a#.nomos.provider.v1.ShutdownResponseBRZPgithub.com/autonomous-bits/nomos-provider-environment-variables/proto/providerv1b\x06proto3"

var (
	file_proto_provider_proto_rawDescOnce sync.Once
	file_proto_provider_proto_rawDescData []byte
)

func file_proto_provider_proto_rawDescGZIP() []byte {
	file_proto_provider_proto_rawDescOnce.Do(func() {
		file_proto_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_provider_proto_rawDesc), len(file_proto_provider_proto_rawDesc)))
	})
	return file_proto_provider_proto_rawDescData
}

var file_proto_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_provider_proto_goTypes = []any{
	(HealthStatus)(0),        // 0: nomos.provider.v1.HealthStatus
	(*InitRequest)(nil),      // 1: nomos.provider.v1.InitRequest
	(*InitResponse)(nil),     // 2: nomos.provider.v1.InitResponse
	(*FetchRequest)(nil),     // 3: nomos.provider.v1.FetchRequest
	(*FetchResponse)(nil),    // 4: nomos.provider.v1.FetchResponse
	(*InfoRequest)(nil),      // 5: nomos.provider.v1.InfoRequest
	(*InfoResponse)(nil),     // 6: nomos.provider.v1.InfoResponse
	(*HealthRequest)(nil),    // 7: nomos.provider.v1.HealthRequest
	(*HealthResponse)(nil),   // 8: nomos.provider.v1.HealthResponse
	(*ShutdownRequest)(nil),  // 9: nomos.provider.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 10: nomos.provider.v1.ShutdownResponse
	(*structpb.Struct)(nil),  // 11: google.protobuf.Struct
}
var file_proto_provider_proto_depIdxs = []int32{
	11, // 0: nomos.provider.v1.InitRequest.config:type_name -> google.protobuf.Struct
	11, // 1: nomos.provider.v1.FetchResponse.value:type_name -> google.protobuf.Struct
	0,  // 2: nomos.provider.v1.HealthResponse.status:type_name -> nomos.provider.v1.HealthStatus
	1,  // 3: nomos.provider.v1.ProviderService.Init:input_type -> nomos.provider.v1.InitRequest
	3,  // 4: nomos.provider.v1.ProviderService.Fetch:input_type -> nomos.provider.v1.FetchRequest
	5,  // 5: nomos.provider.v1.ProviderService.Info:input_type -> nomos.provider.v1.InfoRequest
	7,  // 6: nomos.provider.v1.ProviderService.Health:input_type -> nomos.provider.v1.HealthRequest
	9,  // 7: nomos.provider.v1.ProviderService.Shutdown:input_type -> nomos.provider.v1.ShutdownRequest
	2,  // 8: nomos.provider.v1.ProviderService.Init:output_type -> nomos.provider.v1.InitResponse
	4,  // 9: nomos.provider.v1.ProviderService.Fetch:output_type -> nomos.provider.v1.FetchResponse
	6,  // 10: nomos.provider.v1.ProviderService.Info:output_type -> nomos.provider.v1.InfoResponse
	8,  // 11: nomos.provider.v1.ProviderService.Health:output_type -> nomos.provider.v1.HealthResponse
	10, // 12: nomos.provider.v1.ProviderService.Shutdown:output_type -> nomos.provider.v1.ShutdownResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_provider_proto_init() }
func file_proto_provider_proto_init() {
	if File_proto_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_provider_proto_rawDesc), len(file_proto_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_provider_proto_goTypes,
		DependencyIndexes: file_proto_provider_proto_depIdxs,
		EnumInfos:         file_proto_provider_proto_enumTypes,
		MessageInfos:      file_proto_provider_proto_msgTypes,
	}.Build()
	File_proto_provider_proto = out.File
	file_proto_provider_proto_goTypes = nil
	file_proto_provider_proto_depIdxs = nil
}
